# Generated by Django 3.2.16 on 2023-02-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
