# Generated by Django 3.2.16 on 2023-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(default='', upload_to='feedback_image'),
        ),
    ]
