# Generated by Django 3.2.16 on 2022-11-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='contact',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
