# Generated by Django 3.2.16 on 2022-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0002_auto_20221114_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='smartbin',
        ),
    ]
