# Generated by Django 3.2.16 on 2022-11-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0003_rename_user_smartbin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartbin',
            old_name='depth',
            new_name='height',
        ),
    ]
