# Generated by Django 3.2.16 on 2022-11-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0005_smartbin_map_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartbin',
            name='map_location',
        ),
    ]
