# Generated by Django 3.2.16 on 2022-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0006_remove_smartbin_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='map_location',
            field=models.TextField(null=True),
        ),
    ]
