# Generated by Django 3.2.16 on 2022-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0007_smartbin_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
