# Generated by Django 3.2.16 on 2023-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0008_smartbin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
