# Generated by Django 3.2.16 on 2023-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0010_smartbin_h_a_m_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='h_a_m_sent',
            field=models.CharField(default='not', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='status',
            field=models.CharField(default='empty', max_length=10, null=True),
        ),
    ]
