# Generated by Django 3.2.16 on 2023-02-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0011_auto_20230223_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartbin',
            name='date',
        ),
    ]
