# Generated by Django 3.2.16 on 2023-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbins', '0012_remove_smartbin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
